- name: ping the server
  hosts: frontend

  tasks:
  - name: ping
    ansible.builtin.ping:

# [local]
# localhost
# 54.87.144.252

# [frontend]
# 54.87.144.252

# [cart]
# 172.31.77.200

# [catalogue]
# 172.31.77.200

# [local:vars]
# NAME=from inventory