# - name: ping the server
#   hosts: frontend

#   tasks:
#   - name: ping
#     ansible.builtin.ping:

[local]
localhost
54.87.144.252

[frontend]
54.87.144.252

[cart]
54.87.144.252

[catalogue]
54.87.144.252

[local:vars]
NAME=from inventory